name: 📝 Tracking Issue
description: This is a template of a large tracking issue. Used to visualize and organize large fetaures or time blocks of work.
title: "[TRACKING]: "
labels: [tracking]
projects: ["MMBZ Planning"]


body:
  - type: markdown
    attributes:
      value: |
        This is a large work tracking issue.

  - type: textarea
    id: tracking-items
    attributes:
      label: Tracked issues
      description: List all of the issues that belong to this tracking issue
      placeholder: [ ] issue #
    validations:
      required: true
